- hosts: aws
  become: yes
  become_method: sudo
  vars_files:
    - vars/vault.yml
    - vars/default.yml
  tasks:
    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

  roles:
    # - roles/install_nginx
    # - roles/install_maria_db
    # - roles/install_php
    # - roles/wp-cli-install
    - roles/wordpress

  
