---
# tasks file for wp-cli-istall

- name: Setup wp-cli
  get_url:
    url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
    dest: /tmp/wp-cli.phar
    mode: 0755
  tags: wp-cli

- name: Move wp-cli
  command: mv /tmp/wp-cli.phar /usr/local/bin/wp


